//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class StaffWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dal.ServiceReference1.WorkPositionWCF WorkPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dal.ServiceReference1.WorkPositionWCF WorkPosition {
            get {
                return this.WorkPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPositionField, value) != true)) {
                    this.WorkPositionField = value;
                    this.RaisePropertyChanged("WorkPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkPositionWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class WorkPositionWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dal.ServiceReference1.StaffWCF[] StaffField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dal.ServiceReference1.StaffWCF[] Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteOffMaterialsWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class WriteOffMaterialsWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dal.ServiceReference1.MaterialsWCF MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsedQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dal.ServiceReference1.MaterialsWCF Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsedQuantity {
            get {
                return this.UsedQuantityField;
            }
            set {
                if ((this.UsedQuantityField.Equals(value) != true)) {
                    this.UsedQuantityField = value;
                    this.RaisePropertyChanged("UsedQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterialsWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.ShadowsWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.BalsamWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.ShampooWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.LaqueWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.ColorWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.FoundationWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.PowderWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.MascaraWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.LipstickWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.NailTopWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.NailPolishWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Dal.ServiceReference1.NailBaseWCF))]
    public partial class MaterialsWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dal.ServiceReference1.ServicesWCF[] BllServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityBottlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityGeneralVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuntityCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dal.ServiceReference1.ServicesWCF[] BllServices {
            get {
                return this.BllServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.BllServicesField, value) != true)) {
                    this.BllServicesField = value;
                    this.RaisePropertyChanged("BllServices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantityBottles {
            get {
                return this.QuantityBottlesField;
            }
            set {
                if ((this.QuantityBottlesField.Equals(value) != true)) {
                    this.QuantityBottlesField = value;
                    this.RaisePropertyChanged("QuantityBottles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QuantityGeneralVolume {
            get {
                return this.QuantityGeneralVolumeField;
            }
            set {
                if ((this.QuantityGeneralVolumeField.Equals(value) != true)) {
                    this.QuantityGeneralVolumeField = value;
                    this.RaisePropertyChanged("QuantityGeneralVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QuntityCount {
            get {
                return this.QuntityCountField;
            }
            set {
                if ((this.QuntityCountField.Equals(value) != true)) {
                    this.QuntityCountField = value;
                    this.RaisePropertyChanged("QuntityCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShadowsWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ShadowsWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalsamWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class BalsamWCF : Dal.ServiceReference1.MaterialsWCF {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShampooWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ShampooWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaqueWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class LaqueWCF : Dal.ServiceReference1.MaterialsWCF {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ColorWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoundationWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class FoundationWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PowderWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class PowderWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MascaraWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class MascaraWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LipstickWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class LipstickWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NailTopWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class NailTopWCF : Dal.ServiceReference1.MaterialsWCF {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NailPolishWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class NailPolishWCF : Dal.ServiceReference1.MaterialsWCF {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NailBaseWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class NailBaseWCF : Dal.ServiceReference1.MaterialsWCF {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicesWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ServicesWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dal.ServiceReference1.MaterialsWCF[] WCFMaterialsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dal.ServiceReference1.MaterialsWCF[] WCFMaterials {
            get {
                return this.WCFMaterialsField;
            }
            set {
                if ((object.ReferenceEquals(this.WCFMaterialsField, value) != true)) {
                    this.WCFMaterialsField = value;
                    this.RaisePropertyChanged("WCFMaterials");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class InfoWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionTime {
            get {
                return this.ActionTimeField;
            }
            set {
                if ((this.ActionTimeField.Equals(value) != true)) {
                    this.ActionTimeField = value;
                    this.RaisePropertyChanged("ActionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputParameters {
            get {
                return this.InputParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.InputParametersField, value) != true)) {
                    this.InputParametersField = value;
                    this.RaisePropertyChanged("InputParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputParameters {
            get {
                return this.OutputParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputParametersField, value) != true)) {
                    this.OutputParametersField = value;
                    this.RaisePropertyChanged("OutputParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserAutorization", ReplyAction="http://tempuri.org/IService1/GetUserAutorizationResponse")]
        Dal.ServiceReference1.StaffWCF GetUserAutorization(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserAutorization", ReplyAction="http://tempuri.org/IService1/GetUserAutorizationResponse")]
        System.Threading.Tasks.Task<Dal.ServiceReference1.StaffWCF> GetUserAutorizationAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WritingOff", ReplyAction="http://tempuri.org/IService1/WritingOffResponse")]
        string[] WritingOff(Dal.ServiceReference1.WriteOffMaterialsWCF[] writeOffMaterials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WritingOff", ReplyAction="http://tempuri.org/IService1/WritingOffResponse")]
        System.Threading.Tasks.Task<string[]> WritingOffAsync(Dal.ServiceReference1.WriteOffMaterialsWCF[] writeOffMaterials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServices", ReplyAction="http://tempuri.org/IService1/GetServicesResponse")]
        Dal.ServiceReference1.ServicesWCF[] GetServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServices", ReplyAction="http://tempuri.org/IService1/GetServicesResponse")]
        System.Threading.Tasks.Task<Dal.ServiceReference1.ServicesWCF[]> GetServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPositions", ReplyAction="http://tempuri.org/IService1/GetListPositionsResponse")]
        Dal.ServiceReference1.WorkPositionWCF[] GetListPositions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListPositions", ReplyAction="http://tempuri.org/IService1/GetListPositionsResponse")]
        System.Threading.Tasks.Task<Dal.ServiceReference1.WorkPositionWCF[]> GetListPositionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListMaterials", ReplyAction="http://tempuri.org/IService1/GetListMaterialsResponse")]
        Dal.ServiceReference1.MaterialsWCF[] GetListMaterials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListMaterials", ReplyAction="http://tempuri.org/IService1/GetListMaterialsResponse")]
        System.Threading.Tasks.Task<Dal.ServiceReference1.MaterialsWCF[]> GetListMaterialsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        void DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployees", ReplyAction="http://tempuri.org/IService1/GetEmployeesResponse")]
        Dal.ServiceReference1.StaffWCF[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployees", ReplyAction="http://tempuri.org/IService1/GetEmployeesResponse")]
        System.Threading.Tasks.Task<Dal.ServiceReference1.StaffWCF[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        void AddEmployee(Dal.ServiceReference1.StaffWCF staffWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(Dal.ServiceReference1.StaffWCF staffWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMaterials", ReplyAction="http://tempuri.org/IService1/AddMaterialsResponse")]
        void AddMaterials(Dal.ServiceReference1.MaterialsWCF materialsWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMaterials", ReplyAction="http://tempuri.org/IService1/AddMaterialsResponse")]
        System.Threading.Tasks.Task AddMaterialsAsync(Dal.ServiceReference1.MaterialsWCF materialsWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChangedQuantity", ReplyAction="http://tempuri.org/IService1/GetChangedQuantityResponse")]
        void GetChangedQuantity(int QuantityBottles, double QuantityGeneralVolume, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChangedQuantity", ReplyAction="http://tempuri.org/IService1/GetChangedQuantityResponse")]
        System.Threading.Tasks.Task GetChangedQuantityAsync(int QuantityBottles, double QuantityGeneralVolume, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMaterials", ReplyAction="http://tempuri.org/IService1/UpdateMaterialsResponse")]
        void UpdateMaterials(Dal.ServiceReference1.MaterialsWCF materialsWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMaterials", ReplyAction="http://tempuri.org/IService1/UpdateMaterialsResponse")]
        System.Threading.Tasks.Task UpdateMaterialsAsync(Dal.ServiceReference1.MaterialsWCF materialsWCF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLoggs", ReplyAction="http://tempuri.org/IService1/GetLoggsResponse")]
        Dal.ServiceReference1.InfoWCF[] GetLoggs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLoggs", ReplyAction="http://tempuri.org/IService1/GetLoggsResponse")]
        System.Threading.Tasks.Task<Dal.ServiceReference1.InfoWCF[]> GetLoggsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Dal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Dal.ServiceReference1.IService1>, Dal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dal.ServiceReference1.StaffWCF GetUserAutorization(string login, string password) {
            return base.Channel.GetUserAutorization(login, password);
        }
        
        public System.Threading.Tasks.Task<Dal.ServiceReference1.StaffWCF> GetUserAutorizationAsync(string login, string password) {
            return base.Channel.GetUserAutorizationAsync(login, password);
        }
        
        public string[] WritingOff(Dal.ServiceReference1.WriteOffMaterialsWCF[] writeOffMaterials) {
            return base.Channel.WritingOff(writeOffMaterials);
        }
        
        public System.Threading.Tasks.Task<string[]> WritingOffAsync(Dal.ServiceReference1.WriteOffMaterialsWCF[] writeOffMaterials) {
            return base.Channel.WritingOffAsync(writeOffMaterials);
        }
        
        public Dal.ServiceReference1.ServicesWCF[] GetServices() {
            return base.Channel.GetServices();
        }
        
        public System.Threading.Tasks.Task<Dal.ServiceReference1.ServicesWCF[]> GetServicesAsync() {
            return base.Channel.GetServicesAsync();
        }
        
        public Dal.ServiceReference1.WorkPositionWCF[] GetListPositions() {
            return base.Channel.GetListPositions();
        }
        
        public System.Threading.Tasks.Task<Dal.ServiceReference1.WorkPositionWCF[]> GetListPositionsAsync() {
            return base.Channel.GetListPositionsAsync();
        }
        
        public Dal.ServiceReference1.MaterialsWCF[] GetListMaterials() {
            return base.Channel.GetListMaterials();
        }
        
        public System.Threading.Tasks.Task<Dal.ServiceReference1.MaterialsWCF[]> GetListMaterialsAsync() {
            return base.Channel.GetListMaterialsAsync();
        }
        
        public void DeleteProduct(int id) {
            base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public Dal.ServiceReference1.StaffWCF[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<Dal.ServiceReference1.StaffWCF[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public void AddEmployee(Dal.ServiceReference1.StaffWCF staffWCF) {
            base.Channel.AddEmployee(staffWCF);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(Dal.ServiceReference1.StaffWCF staffWCF) {
            return base.Channel.AddEmployeeAsync(staffWCF);
        }
        
        public void AddMaterials(Dal.ServiceReference1.MaterialsWCF materialsWCF) {
            base.Channel.AddMaterials(materialsWCF);
        }
        
        public System.Threading.Tasks.Task AddMaterialsAsync(Dal.ServiceReference1.MaterialsWCF materialsWCF) {
            return base.Channel.AddMaterialsAsync(materialsWCF);
        }
        
        public void GetChangedQuantity(int QuantityBottles, double QuantityGeneralVolume, int id) {
            base.Channel.GetChangedQuantity(QuantityBottles, QuantityGeneralVolume, id);
        }
        
        public System.Threading.Tasks.Task GetChangedQuantityAsync(int QuantityBottles, double QuantityGeneralVolume, int id) {
            return base.Channel.GetChangedQuantityAsync(QuantityBottles, QuantityGeneralVolume, id);
        }
        
        public void UpdateMaterials(Dal.ServiceReference1.MaterialsWCF materialsWCF) {
            base.Channel.UpdateMaterials(materialsWCF);
        }
        
        public System.Threading.Tasks.Task UpdateMaterialsAsync(Dal.ServiceReference1.MaterialsWCF materialsWCF) {
            return base.Channel.UpdateMaterialsAsync(materialsWCF);
        }
        
        public Dal.ServiceReference1.InfoWCF[] GetLoggs() {
            return base.Channel.GetLoggs();
        }
        
        public System.Threading.Tasks.Task<Dal.ServiceReference1.InfoWCF[]> GetLoggsAsync() {
            return base.Channel.GetLoggsAsync();
        }
    }
}
